trigger:
- main
- development

resources:
  - repo: self

variables:
  - group: sicredi-azure-pipelines-ci-variables
  - group: monitor-pgto-tributos-frontend-dev

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureStaticWebApp@0
  displayName: Deploy Azure Static WebApp
  inputs:
    app_location: '/'
    api_location: ''
    output_location: 'dist'
  env:
    azure_static_web_apps_api_token: $(deploymentToken)